version: "3.8"
services:
  mongodb-limao:
    image: docker.io/mongo:focal
    command: ["/bin/sh", "-c", "mongod --replSet=rs0 --port 27017 --bind_ip_all"]
    container_name: mongodb-limao
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - mongodb-limao-data:/data/db
    networks:
    - mongodb_network
    ports:
    - 27017:27017
    #healthcheck:
    #  test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    restart: unless-stopped

  mongodb-laranja:
    image: docker.io/mongo:focal
    command: ["/bin/sh", "-c", "mongod --replSet=rs0 --port 27018 --bind_ip_all"]
    container_name: mongodb-laranja
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - mongodb-laranja-data:/data/db
    networks:
    - mongodb_network
    ports:
    - 27018:27018
    #healthcheck:
    #  test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    restart: unless-stopped

  mongodb-lima:
    image: docker.io/mongo:focal
    command: ["/bin/sh", "-c", "mongod --replSet=rs0 --port 27019 --bind_ip_all"]
    container_name: mongodb-lima
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - mongodb-lima-data:/data/db
    networks:
    - mongodb_network
    ports:
    - 27019:27019
    #healthcheck:
    #  test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3
    restart: unless-stopped  

volumes:
  mongodb-limao-data:
    name: mongodb-limao-data
  mongodb-laranja-data:
    name: mongodb-laranja-data
  mongodb-lima-data:
    name: mongodb-lima-data  
networks:
  mongodb_network:
    name: mongodb_network